
name: Buiding Spring Boot Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Check directory structure at root
        run: ls -l

      - name: Changing directory to APIGateway and Build Jar File
        run: |
          cd APIGateway
          mvn clean install

      - name: Changing directory to Service Registry and Build Jar File
        run: |
          cd ServiceRegistry
          mvn clean install

      - name: Changing directory to User Service and Build Jar File
        run: |
          cd UserService
          mvn clean install
