name: Building Spring Boot Projects

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check directory structure at root
        run: ls -l

      - name: Loop through directories and build projects
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "Processing $dir"
              cd "$dir"
              ls -l
              mvn clean install
              cd ..
            fi
          done
