
name: Buiding Spring Boot Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Check directory structure at root
        run: ls -l

      - name: Changed directory to APIGateway and Build Jar File
        run: |
          cd APIGateway
          ls -l
          mvn clean install

      - name: Changed directory to HotelService and Build Jar File
        run: |
          cd HotelService
          ls -l
          mvn clean install


